import Foundation
import Testing
@testable import TechCalcCore

/// One entry of the TI-84 Plus CE benchmark suite.
///
/// `provenance` is optional *here* so that a fixture missing one can be reported as a build
/// error by `everyFixtureCarriesProvenance` rather than failing to decode with no explanation.
struct BenchmarkCase: Decodable, Sendable {
    let id: String
    let group: String
    /// Lines entered before the expression, e.g. storing a list and running a STAT command.
    let setup: [String]?
    /// The line whose value is asserted.
    let expression: String
    let provenance: String?
    let expected: Double?
    let tolerance: Double?
    /// The TI error name, for the cases where erroring *is* the expected behaviour.
    let expectedError: String?
    /// The string the calculator should display, for display parity.
    let expectedDisplay: String?
}

struct BenchmarkDocument: Decodable, Sendable {
    let schema: Int
    let generator: String
    let reference: String
    let cases: [BenchmarkCase]
}

/// The TI-84 Plus CE benchmark suite.
///
/// Every expected value in the fixture file was produced by R 4.5.3 or by the TI guidebook's
/// documented rule evaluated in R — never by running tech-calc. The fixture file is generated by
/// `~/.claude/scripts/techcalc-fixtures.R`.
@Suite("TI-84 benchmark fixtures")
struct BenchmarkFixtureTests {

    static let document: BenchmarkDocument = {
        guard let fixture = Bundle.module.url(forResource: "ti84-benchmarks", withExtension: "json"),
              let data = try? Data(contentsOf: fixture),
              let decoded = try? JSONDecoder().decode(BenchmarkDocument.self, from: data) else {
            preconditionFailure("the benchmark fixture suite is missing or unreadable")
        }
        return decoded
    }()

    /// The numeric-parity bar the pre-build decisions set, when a case names no tolerance itself.
    static let defaultTolerance = 1e-9

    @Test("The fixture suite loads and is not empty")
    func suiteLoads() {
        #expect(Self.document.schema == 1)
        #expect(Self.document.cases.count >= 100)
    }

    /// A fixture entry without a provenance field is a build error, and no expected value may
    /// come from the program under test.
    @Test("Every fixture entry carries a provenance that is not tech-calc itself")
    func everyFixtureCarriesProvenance() {
        for benchmark in Self.document.cases {
            guard let provenance = benchmark.provenance, !provenance.isEmpty else {
                Issue.record("fixture \(benchmark.id) has no provenance")
                continue
            }
            let lowercased = provenance.lowercased()
            #expect(!lowercased.contains("tech-calc"), "fixture \(benchmark.id) cites the code under test")
            #expect(!lowercased.contains("techcalc"), "fixture \(benchmark.id) cites the code under test")
        }
    }

    @Test("Every fixture asserts something")
    func everyFixtureAsserts() {
        for benchmark in Self.document.cases {
            let asserts = benchmark.expected != nil
                || benchmark.expectedError != nil
                || benchmark.expectedDisplay != nil
            #expect(asserts, "fixture \(benchmark.id) asserts nothing")
        }
    }

    @Test("Every benchmark case matches its independently sourced expected value",
          arguments: BenchmarkFixtureTests.document.cases)
    func benchmark(_ benchmark: BenchmarkCase) throws {
        var calculator = Fixture.calculator()

        for line in benchmark.setup ?? [] {
            let entry = calculator.enter(line)
            #expect(entry.errorName == nil, "\(benchmark.id): setup \"\(line)\" gave \(entry.display)")
        }

        if let expectedError = benchmark.expectedError {
            let entry = calculator.enter(benchmark.expression)
            #expect(entry.errorName == expectedError,
                    "\(benchmark.id): \"\(benchmark.expression)\" gave \(entry.display)")
            return
        }

        let entry = calculator.enter(benchmark.expression)
        #expect(entry.errorName == nil, "\(benchmark.id): \"\(benchmark.expression)\" gave \(entry.display)")

        if let expected = benchmark.expected {
            let actual = try calculator.context.ans.value.asReal
            expectClose(
                actual, expected,
                tolerance: benchmark.tolerance ?? Self.defaultTolerance,
                "\(benchmark.id) [\(benchmark.group)]: \(actual) is not \(expected) (\(benchmark.provenance ?? "-"))"
            )
        }

        if let expectedDisplay = benchmark.expectedDisplay {
            #expect(entry.display == expectedDisplay, "\(benchmark.id): display parity")
        }
    }
}
